# Generated by Django 3.2 on 2021-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
