# Generated by Django 3.2 on 2022-09-10 09:21

import caldav_framework.example.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_calendar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=caldav_framework.example.fields.ColorField(default=caldav_framework.example.fields.random_color, max_length=9),
        ),
    ]
